Implement Framebuffer API for Drawing Primitives and Text Rendering
CharlotteOS-Deprecated/charlotte-core pull request #21
Opened 2024-02-08 01:25 UTC by shelovesmox

This pull request introduces a comprehensive update to the OS's graphics capabilities by implementing a framebuffer API that supports drawing basic geometric primitives and text rendering. The following key features have been added:

- **Rectangle Drawing**: Allows for the creation of filled rectangles, customizable with color parameters.
- **Triangle Drawing**: Supports the rendering of filled triangles, also customizable with colors.
- **Text Rendering**: Implements functionality for rendering text in various fonts and sizes
- **Color Support**: Enhances graphical applications by enabling a wide range of colors for all drawable elements.
- **Number Display**: Facilitates the display of numerical data directly through the framebuffer, useful for creating interfaces that require the presentation of numerical information.

These enhancements are aimed at providing a more robust foundation for debugging the operating system and drawing basic graphics.

2024-02-08 03:24 UTC, EthanPlant requested changes

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/framebuffer/framebuffer.rs
Should probably add some doc comments to the structures and functions.

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/framebuffer/chars.rs
We might want to extend the font to the entire ASCII charset. These characters should be fine for now though.

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/framebuffer/framebuffer.rs
> +use crate::chars::*;
I *think* we just need to import `chars::{get_char_bitmap, FONT_WIDTH, FONT_HEIGHT}` instead of the entire file. We don't need to be pulling in the bitmap for every character as well.

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/framebuffer/framebuffer.rs
> +fn blend_colors(foreground: u32, background: u32, blend_factor: u8) -> u32 {
We could probably move this function into a dedicated color file, maybe we could also predefine some common colors as constants.

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/framebuffer/framebuffer.rs
> +     unsafe fn draw_line(&self, p0: Point, p1: Point, color: u32) {
Do these functions need to be declared `unsafe`?

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/framebuffer/framebuffer.rs
> +    pub unsafe fn clear_screen(&self, color: u32) {
Instead of declaring the entire function `unsafe`, we should probably be just wrapping the pointer dereference in an unsafe block, the same applies for `draw_pixel`.

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/framebuffer/framebuffer.rs
> +            let pixel_offset = y * self.pitch / (self.bpp / 8) + x;
Shouldn't it be `self.pitch * (self.bpp / 8)`?

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/framebuffer/framebuffer.rs
> +                x += FONT_WIDTH + 1; // Plus 1 for a gap between characters
We could instead create a space character of all 0s and just draw that onto the screen, this works for now though.

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/framebuffer/framebuffer.rs
> +                x = start_x;
Should we be resetting x back to the beginning of the string, or the beginning of a line?

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/framebuffer/framebuffer.rs
> +    pub unsafe fn draw_char(&self, x: usize, y: usize, bitmap: &[u8; FONT_HEIGHT], color: u32) {
This potentially could instead take in a character and grab the bitmap itself

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/framebuffer/framebuffer.rs
> +            if c == ' ' {
Could we possibly use a match statement for this instead?

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/main.rs
> +use framebuffer::*;
Should avoid a wildcard import, we only need to pull in `framebuffer::framebuffer{Points, init_framebuffer}`

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/framebuffer/framebuffer.rs
> +use core::fmt::write;
Not being used.

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/framebuffer/framebuffer.rs
> +use crate::chars::*;
This should also be `use crate::framebuffer::chars`

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/framebuffer/chars.rs
Do the character bitmaps need to be public?

2024-02-08 03:24 UTC, EthanPlant commented on charlotte_core/src/main.rs
> +use crate::framebuffer::framebuffer::*;
This is unneeded.

2024-02-08 03:47 UTC, mdpatelcsecon commented on charlotte_core/src/framebuffer/chars.rs
I agree we should support all of ASCII for kernel logging.

We will eventually want unicode but that can wait until we start work on a proper GUI which will most likely run in userspace.

2024-02-08 06:01 UTC, mdpatelcsecon commented
Is this ready to merge or are some if the requested changes still undone?

2024-02-09 01:16 UTC, EthanPlant approved these changes

2024-02-09 01:17 UTC, merged